version: "3"
services:
    selenium:
        image: selenium/standalone-chrome
        ports:
        - 4444:4444
    tdportfolioserver:
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
            - 5000:5000
            - 5678:5678
        volumes:
            - .:/app:cached