version: "3"
services:
    selenium:
        image: selenium/standalone-chrome
        ports:
            - "0.0.0.0:4444:4444"
        networks:
            - server-network
    tdportfolioserver:
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
            - "0.0.0.0:5000:5000"
            - "0.0.0.0:5678:5678"
        volumes:
            - .:/app:cached
        networks:
            - server-network
networks:
    server-network:
      external: true